// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmlVubfxR9Fzd2iEwcSleml398eRidZN8',
    appId: '1:735362682890:android:12fddcd3d7b41e348b8ff3',
    messagingSenderId: '735362682890',
    projectId: 'fir-53adb',
    storageBucket: 'fir-53adb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXRzLuxvqxgZC5mGhu25j1n3_0FMZjtUM',
    appId: '1:735362682890:ios:3bbcc1f6417c5acc8b8ff3',
    messagingSenderId: '735362682890',
    projectId: 'fir-53adb',
    storageBucket: 'fir-53adb.appspot.com',
    androidClientId: '735362682890-m5klaaq85hn5p4c48ddshlp771l2a5kt.apps.googleusercontent.com',
    iosClientId: '735362682890-r4jfucnk45308e1clfrm6vqqte0o6c60.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookKeeper',
  );
}
